#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use CMD\mysql\CreateMySqlUserCommand;
use CMD\rds\PurgeRDSSnapshotCommand;
use CMD\s3\CreateS3BucketCommand;
use CMD\sites\CreateSiteCommand;
use Symfony\Component\Console\Application;

$application = new Application('Jarvis', '1.0.0');

$application->addCommands([
    new CreateMySqlUserCommand(),
    new CreateS3BucketCommand(),
    new CreateSiteCommand(),
    new PurgeRDSSnapshotCommand(),
]);

try {
    $application->run();
} catch (Exception $e) {
    print $e->getMessage();
}